### ISSUE TITLE
run time issue

### ISSUE THREAD

**Issue by ydduanran** [3DGenomes/TADpole#2]
hello,I am trying to run this program but not able to execute due to this error, please look
Error in scores[pc, 1:length(calinhara_score[[pc]])] <- calinhara_score[[pc]] : 
  number of items to replace is not a multiple of replacement length

**Comment by nanakiksc** [comment]
Hello @ydduanran , thanks for the feedback.

It would be very helpful if you could provide us with a minimal example of the code that generated this error as well as the input data you used, without this information it's really not possible to discover the cause of the error, but it likely seems related to some sort of malformed or otherwise unexpected input.

As troubleshooting steps that you may want to try, 1) please make sure you have installed the latest version of TADpole and 2) make sure your input exactly follows the supported format specified in the README.
