### ISSUE TITLE
How to limit memory or cpu usage?

### ISSUE THREAD

**Issue by zhyanlin** [3DGenomes/TADpole#3]
Hello,

I am running TADpole to analyze chr6 of the combined gm12878 (Rao et al. 2014) HiC data at 10kb resolution. Our server has 96 cores and 768G memory. TADpole uses all CPUs and runs into out-of-memory issues. Would reducing the number of CPUs used help to reduce the memory and if so, have to do it? 

I tried `taskset -c 1-20` and got the following error:

Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
Calls: TADpole ... <Anonymous> -> <Anonymous> -> mclapply -> lapply -> FUN -> mcfork
Execution halted
Error while shutting down parallel: unable to terminate some child processes

**Comment by nanakiksc** [comment]
Hi @zhyanlin , you are right, TADpole uses all available cores and builds as many trees in parallel during the optimization process. We have created a hotfix in the development repository https://github.com/paulasoler/TADpole, but the stable version does not include this feature yet, and the documentation is also not yet updated.

Please download and install the development version of TADpole from the development repository linked above, and use the parameter `cores` to select the number of cores that you want to use. Following the example in the README:
```
library(TADpole)
mat_file <- system.file("extdata", "raw_chr18_300_500_30kb.tsv", package = "TADpole")

tadpole <- TADpole(mat_file, chr = "chr18", start = 9000000, end = 15000000, resol = 30000, cores = 4)
```
should run TADpole using only 4 cores. If you find otherwise, any feedback will be greatly appreciated.
